# Site settings
title: nonamenix@angara
email: nonamenix@gmail.com
description: Yet another home page in the Internet.
baseurl: ""
url: "http://nonamenix.ru"
twitter_username: nonamenix
github_username:  nonamenix

# Build settings
markdown: kramdown
